language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  APP_ENV: local
  env: local

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - php artisan migrate --force --package=cartalyst/sentinel --env=local
  - php artisan migrate --force --env=local
  - php artisan db:seed --force --env=local

script: vendor/bin/phpunit --verbose

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
