language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  APP_ENV: local

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - php artisan migrate --package=cartalyst/sentinel --force
  - php artisan migrate --force
  - php artisan db:seed --force

script: vendor/bin/phpunit --verbose

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
